version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'live'
    default_assignees:
      - 'neolitec'
      - 'whispyy'
    automerged_updates:
      - match:
          dependency_type: 'development'
          update_type: 'semver:minor'
      - match:
          dependency_type: 'production'
          update_type: 'semver:patch'
    # ignored_updates:
    #   - match:
    #       dependency_name: 'example'
    #       # The version_requirement specifies the versions to ignore.
    #       # The range format is specific to the package manager
    #       # (e.g., ^1.0.0 for JS, or ~> 2.0 for Ruby).
    #       version_requirement: '7.x'